
name : MIGLE CRM Backend SpringBoot Build & Push
# 1. 이벤트 트리거 (on)
on :
  push :
    branches : [main]

# 2. jobs - runner
jobs :
  build :
    runs-on : ubuntu-latest
    # 3. source checkout
    steps :
      - name : Source Checkout
        uses : actions/checkout@v2
      # 4. setup node
      - name : Setup Node
        uses : actions/setup-node@v2

      # 5. docker build
      - name : Docker buildx
        uses : docker/setup-buildx-action@v2

      # 6. docker login
      - name : Docker Login
        uses : docker/login-action@v2
        with : # 제거에 들어옵니다(thinghoon) 여러분들의 도커허브 시크릿키를 등록하시고 아래 이름을 바꿔주세요
          username : ${{ secrets.DOCKERHUB_USER_TH }}
          password : ${{ secrets.DOCKERHUB_TOKEN_TH }}

      # 7. docker build and push
      - name : Docker push
        uses : docker/build-push-action@v2
        with :
          context : ./backend/minglecrm/
          file : ./backend/minglecrm/Dockerfile
          push : true
          # 제거에 들어옵니다(thinghoon) 여러분들의 도커허브 시크릿키를 등록하시고 아래 이름을 바꿔주세요
          tags : ${{ secrets.DOCKERHUB_USER_TH }}/mingle_backend_springboot:${{github.sha}}
